"""
Django settings for InvoiceDiscounting project.

Generated by 'django-admin startproject' using Django 5.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from dotenv import load_dotenv
import os, dj_database_url

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-*2x9gy+z9$r@8qd2zjq1cfnegpyld(z#)te_+ls(v6*3%t+snu'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['tokenizedinvoicediscounting-production.up.railway.app', 'localhost','127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'rest_framework_simplejwt.token_blacklist',
    'drf_spectacular',
    'corsheaders',
    'discounting',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Disable CSRF for API endpoints
CSRF_COOKIE_SECURE = False
CSRF_USE_SESSIONS = False

ROOT_URLCONF = 'InvoiceDiscounting.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'InvoiceDiscounting.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases
if os.getenv('ENV') == 'production':
    DATABASES = {
        'default': dj_database_url.parse(
            f"{os.getenv('DATABASE_URL')}",
            conn_max_age=600,
            conn_health_checks=True,
        )
    }
else:
    DATABASES = {
        'default': dj_database_url.parse(
            f"{os.getenv('DATABASE_LOCAL_URL')}",
            conn_max_age=600,
            conn_health_checks=True,
        )
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'discounting.User'

# Media files (file uploads)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 20,
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
}

# Simple JWT settings
from datetime import timedelta

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'UPDATE_LAST_LOGIN': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_HEADER_NAME': 'HTTP_AUTHORIZATION',
    'USER_ID_FIELD': 'id',
    'USER_ID_CLAIM': 'user_id',
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
    'TOKEN_TYPE_CLAIM': 'token_type',
}

# CORS settings for frontend integration
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://invoice-discounting-frontend-steel.vercel.app"
]

CORS_ALLOW_CREDENTIALS = True

# Allow all origins in development
CORS_ALLOW_ALL_ORIGINS = DEBUG

# drf-spectacular settings
SPECTACULAR_SETTINGS = {
    'TITLE': 'Invoice Discounting Platform API',
    'DESCRIPTION': """
    API for the Tokenized Invoice Discounting Platform - A blockchain-enabled platform for invoice financing.

    ## Key Features

    ### 🤖 OCR Invoice Extraction
    Automatically extract invoice data from eTIMS invoices using OCR technology:
    - Upload PDF or image files (JPG, PNG)
    - Extract invoice numbers, amounts, dates, and KRA PINs
    - Get confidence scores for extracted fields
    - Support for Kenya Revenue Authority eTIMS format

    ### 💰 Invoice Management
    - Submit invoices for discounting
    - Track invoice status (pending, approved, funded, settled)
    - Real-time funding requests
    - Payment tracking with M-Pesa integration

    ### 👥 User Management
    - Multi-role support (Supplier, Buyer, Financier)
    - KYC document verification
    - JWT authentication

    ### 📊 Dashboard & Analytics
    - Real-time statistics
    - Funding history
    - Credit profile tracking

    ## Authentication
    Most endpoints require JWT authentication. Include the access token in the Authorization header:
    ```
    Authorization: Bearer <your_access_token>
    ```

    ## OCR Workflow
    1. **Extract data:** POST to `/api/invoices/extract/` with invoice file
    2. **Review:** Frontend displays extracted data with confidence scores
    3. **Create:** POST to `/api/invoices/` with confirmed data

    Or use the one-step approach:
    - POST directly to `/api/invoices/` with invoice file - OCR runs automatically!
    """,
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,
    'COMPONENT_SPLIT_REQUEST': True,
    'SCHEMA_PATH_PREFIX': '/api/',
    'SWAGGER_UI_SETTINGS': {
        'deepLinking': True,
        'persistAuthorization': True,
        'displayOperationId': True,
        'filter': True,
    },
    'TAGS': [
        {'name': 'Invoice OCR', 'description': 'OCR-powered invoice data extraction from eTIMS documents'},
        {'name': 'Invoices', 'description': 'Invoice management and discounting operations'},
        {'name': 'Authentication', 'description': 'User authentication and JWT token management'},
        {'name': 'Users', 'description': 'User profile and management'},
        {'name': 'KYC', 'description': 'KYC document upload and verification'},
        {'name': 'Contracts', 'description': 'Buyer-Supplier contract management'},
        {'name': 'Payments', 'description': 'Payment tracking and M-Pesa integration'},
        {'name': 'Dashboard', 'description': 'Dashboard statistics and analytics'},
    ],
}

# OCR Configuration
OCR_SETTINGS = {
    'SUPPORTED_FORMATS': ['pdf', 'jpg', 'jpeg', 'png'],
    'MAX_FILE_SIZE': 10 * 1024 * 1024,  # 10MB
    'TESSERACT_CONFIG': '--oem 3 --psm 6',  # LSTM engine, uniform text block
    'TESSERACT_LANG': 'eng',
    'TEMP_UPLOAD_DIR': 'temp/ocr_uploads/',
    'CLEANUP_TEMP_FILES': True,
    'LOG_OCR_ATTEMPTS': True,
}
