# Generated by Django 5.2.8 on 2026-03-02 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discounting', '0002_kycdocument'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='buyer_kra_pin',
            field=models.CharField(blank=True, help_text='Buyer KRA PIN from eTIMS', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kra_verification_date',
            field=models.DateTimeField(blank=True, help_text='When KRA verification was performed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kra_verification_error',
            field=models.TextField(blank=True, help_text='Error message if verification failed', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kra_verification_response',
            field=models.JSONField(blank=True, help_text='Full KRA API response', null=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='kra_verified',
            field=models.BooleanField(default=False, help_text='Verified with KRA eTIMS system'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='supplier_kra_pin',
            field=models.CharField(blank=True, help_text='Supplier KRA PIN from eTIMS', max_length=20, null=True),
        ),
    ]
